apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fleet-llm-d
resources:
  - ../../base
images:
  - name: ghcr.io/llm-d/fleet-agent
    newName: image-registry.openshift-image-registry.svc:5000/fleet-llm-d/fleet-agent
    newTag: latest
  - name: ghcr.io/llm-d/fleet-controller
    newName: image-registry.openshift-image-registry.svc:5000/fleet-llm-d/fleet-controller
    newTag: latest
patches:
  - target:
      kind: Deployment
      name: fleet-agent
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: fleet-agent
      spec:
        template:
          spec:
            containers:
              - name: fleet-agent
                imagePullPolicy: Always
                env:
                  - name: FLEET_CONTROL_PLANE_URL
                    value: http://fleet-controller.fleet-llm-d.svc:8080
                  - name: FLEET_CLUSTER_ID
                    value: oberon-sno
                  - name: FLEET_ROUTING_ENDPOINT
                    value: https://ovms-granite-2b-fleet-llm-d.apps.oberon.fm2aihpcsed.com
                  - name: FLEET_ROUTING_METRICS_ENDPOINT
                    value: https://ovms-granite-2b-fleet-llm-d.apps.oberon.fm2aihpcsed.com
                  - name: FLEET_ROUTING_TLS_SERVER_NAME
                    value: ovms-granite-2b-fleet-llm-d.apps.oberon.fm2aihpcsed.com
