apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resource-telemetry-rbac.yaml
  - resource-telemetry-network-policy.yaml
  - resource-telemetry-job.yaml
  - traffic-job.yaml
